# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cff43b3b2945fad9747d16aa4472d09e2689f4e664f8f4147aab2a579fd15337c6b63f0962a8abbd5cf1f14019b2ed6f1ec4ebb82befbd04d579ad0a9f6dbe8

test:
  secret_key_base: 1585129ecd58451e8172bdc51dccad3d143af60290b43bdb3d37a8b01b7fc2e354454eb8b0f811338c375fcf30f4cbf02773a02e8699dd7b5c2d3351c4bb20ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
